version: '2'

services:
  node1:
    container_name: node1
    image: muta_run
    hostname: node1
    environment:
      - RUST_LOG 
      - RUST_BACKTRACE 
    volumes:
      - ../../../target/docker_target/debug:/app
      - ../../../target:/chain_data
      - .:/chain_config
    networks:
      multiple:
        aliases:
          - node1
        ipv4_address: 172.20.0.11
    command: |
      sh -c '
      cd /chain_config;
      /app/muta -c config-mul-1.toml init genesis.json;'

  node2:
    container_name: node2
    image: muta_run
    hostname: node2
    environment:
      - RUST_LOG 
      - RUST_BACKTRACE 
    depends_on:
      - node1
    volumes:
      - ../../../target/docker_target/debug:/app
      - ../../../target:/chain_data
      - .:/chain_config
    networks:
      multiple:
        aliases:
          - node2
        ipv4_address: 172.20.0.12
    command: |
      sh -c '
      cd /chain_config;
      /app/muta -c config-mul-2.toml init genesis.json;'

networks:
  multiple:
    ipam:
     config:
       - subnet: 172.20.0.0/24