[package]
name = "core-consensus"
version = "0.1.0"
authors = ["Cryptape Technologies <contact@cryptape.com>"]
edition = "2018"

[dependencies]
common-cita = { path = "../../common/cita" }
core-storage = { path = "../storage" }
core-runtime = { path = "../runtime" }
core-types = { path = "../types" }
core-crypto = { path = "../crypto" }
core-merkle = { path = "../merkle" }
core-context = { path = "../context" }
core-serialization = { path = "../serialization" }
core-pubsub = { path = "../pubsub" }

parking_lot = "0.8"
num_cpus = "1.0"
log = "0.4"
tokio = "0.1"
futures-timer = "0.1"
# compat is required for tokio timer
futures-preview = { version = "0.3.0-alpha.16", features = [ "compat" ] }
# TODO: upgrade bft-rs
bft-rs = { git = "https://github.com/cryptape/bft-rs.git", features = [ "verify_req" ], rev = "861aa4f" }
rayon = "1.0"

[dev-dependencies]
hex = "0.3"
components-database = { path = "../../components/database" }
components-transaction-pool = { path = "../../components/transaction-pool" }
components-executor = { path = "../../components/executor" }
