[package]
name = "core-consensus"
version = "0.1.0"
authors = ["Cryptape Technologies <contact@cryptape.com>"]
edition = "2018"

[dependencies]
core-storage = { path = "../storage" }
core-runtime = { path = "../runtime" }
core-types = { path = "../types" }
core-crypto = { path = "../crypto" }
core-merkle = { path = "../merkle" }
core-context = { path = "../context" }
core-serialization = { path = "../serialization" }
core-pubsub = { path = "../pubsub" }

log = "0.4"
tokio = "0.1"
old_futures = { package = "futures", version = "0.1" }
futures-preview = { version = "0.3.0-alpha.14", features = [ "compat" ] }
bft-rs = { git = "https://github.com/cryptape/bft-rs.git", features = [ "verify_req" ], branch = "v0.3" }

[dev-dependencies]
hex = "0.3"
components-database = { path = "../../components/database" }
components-transaction-pool = { path = "../../components/transaction-pool" }
components-executor = { path = "../../components/executor" }
