[package]
name = "core-consensus"
version = "0.1.0"
authors = ["Cryptape Technologies <contact@cryptape.com>"]
edition = "2018"

[dependencies]
core-storage = { path = "../storage" }
core-runtime = { path = "../runtime" }
core-types = { path = "../types" }
core-crypto = { path = "../crypto" }
core-merkle = { path = "../merkle" }

log = "0.4"
futures = "0.1"
futures-locks = "0.3"
tokio = "0.1"

[dev-dependencies]
hex = "0.3"
components-database = { path = "../../components/database" }
components-transaction-pool = { path = "../../components/transaction-pool" }
components-executor = { path = "../../components/executor" }
