[package]
name = "core-merkel"
version = "0.1.0"
authors = ["Cryptape Technologies <contact@cryptape.com>"]
edition = "2018"

[dependencies]
core-types = { path = "../types" }

static_merkel_tree = "1.0.0"
