[package]
name = "muta-chain"
version = "0.1.0"
authors = ["Cryptape Technologies <contact@cryptape.com>"]
edition = "2018"

[dependencies]
protocol = { path = "./protocol" }
core-storage = { path = "./core/storage" }

runtime = "0.3.0-alpha.6"

[workspace]
members = [
  "common/channel",
  "common/config-parser",
  "common/crypto",
  "common/logger",
  "common/merkle",
  "common/metrics",
  "common/pubsub",

  "core/api",
  "core/bank",
  "core/consensus",
  "core/executor",
  "core/mempool",
  "core/network",
  "core/storage",

  "protocol",
]
