[workspace]
members = ["muta"
, "service"
#, "grpc"
#, "examples/pool"
, "examples/monolith-chain"
, "proto"
]

default-members = ["muta"
, "service"
#, "examples/pool"
, "examples/monolith-chain"
, "proto"
]
