[package]
name = "core-merkle"
version = "0.1.0"
authors = ["Cryptape Technologies <contact@cryptape.com>"]
edition = "2018"

[dependencies]
core-types = { path = "../types" }
static_merkle_tree = "1.0.0"
rlp = "0.3"
