[package]
name = "notify"
version = "0.1.0"
authors = ["Cryptape Technologies <contact@cryptape.com>"]
edition = "2018"

[dependencies]
core-types = { path = "../types" }
futures = "0.1"
tokio = "0.1"
