[package]
name = "components-database"
version = "0.1.0"
authors = ["Cryptape Technologies <contact@cryptape.com>"]
edition = "2018"

[dependencies]
core-runtime = { path = "../../core/runtime" }

logger = { path = "../../common/logger" }

log = "0.4"
failure = "0.1"
futures = "0.1"
futures-locks = "0.3"
rocksdb = "0.12.0"
