[package]
name = "core-types"
version = "0.1.0"
authors = ["Cryptape Technologies <contact@cryptape.com>"]
edition = "2018"

[dependencies]
core-serialization = { path = "../serialization" }

hex = "0.3.2"
sha3 = "0.8.0"
numext-fixed-hash-core = "0.1.3"
numext-fixed-hash = "0.1.3"
numext-fixed-uint = "0.1.3"
rlp = "0.3.0"
ethbloom = "0.6.2"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
