[package]
name = "core-types"
version = "0.1.0"
authors = ["Cryptape Technologies <contact@cryptape.com>"]
edition = "2018"

[dependencies]
hex = "0.3"
sha3 = { version="0.8", optional=true }
tiny-keccak = { version="1.4", optional=true }
numext-fixed-hash-core = "0.1"
numext-fixed-hash = "0.1"
numext-fixed-uint = "0.1"
rlp = "0.3"
ethbloom = "0.6"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"

[features]
default = ["hashlib-keccak"]
hashlib-keccak = ["tiny-keccak"]
hashlib-sha3 = ["sha3"]
