[package]
name = "core-storage"
version = "0.1.0"
authors = ["Cryptape Technologies <contact@cryptape.com>"]
edition = "2018"

[dependencies]
core-types = { path = "../types" }
core-runtime = { path = "../runtime" }
core-serialization = { path = "../serialization" }
core-context = { path = "../context" }

bytes = "0.4"
old_futures = { package = "futures", version = "0.1" }
futures-preview = { version = "0.3.0-alpha.16", features = [ "async-await", "nightly", "compat" ] }
byteorder = "1.3"

[dev-dependencies]
components-database = { path = "../../components/database" }
