[package]
name = "core-storage"
version = "0.1.0"
authors = ["Cryptape Technologies <contact@cryptape.com>"]
edition = "2018"

[dependencies]
core-types = { path = "../types" }
core-runtime = { path = "../runtime" }
core-serialization = { path = "../serialization" }

bytes = "0.4.11"
failure = "0.1.3"
futures = "0.1.17"
prost = "0.5.0"
byteorder = "1.3.1"

[dev-dependencies]
components-database = { path = "../../components/database" }
