[package]
name = "core-storage"
version = "0.1.0"
authors = ["Cryptape Technologies <contact@cryptape.com>"]
edition = "2018"

[dependencies]
core-types = { path = "../types" }
core-runtime = { path = "../runtime" }

failure = "0.1.3"
futures = "0.1.17"
