[package]
name = "core-crypto"
version = "0.1.0"
authors = ["Cryptape Technologies <contact@cryptape.com>"]
edition = "2018"

[dependencies]
core-types = { path = "../types" }

secp256k1 = { version = "0.12.2", features = ["rand"] }

[dev-dependencies]
hex = "0.3"
