[package]
name = "core-network"
version = "0.1.0"
authors = ["Cryptape Technologies <contact@cryptape.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
protocol = { path = "../../protocol" }

tentacle = "0.2"
futures-preview = { version = "0.3.0-alpha.18", features = [ "compat" ] }
log = "0.4"
derive_more = "0.15"
tentacle-ping = "0.3"
generic-channel = { version = "0.2", features = [ "all" ] }
tentacle-discovery = "0.2"
parking_lot = "0.9"
rand = "0.7"
futures-timer = "0.3"
runtime = "0.3.0-alpha.7"
snap = "0.2"
async-trait = "0.1"
prost = "0.5"
bytes = { version = "0.4", features = ["serde"] }
serde = "1.0"
serde_derive = "1.0"
bincode = "1.1"

[dev-dependencies]
env_logger = "0.6"
runtime-tokio = "0.3.0-alpha.6"
