[package]
name = "core-network"
version = "0.1.0"
authors = ["Cryptape Technologies <contact@cryptape.com>"]
edition = "2018"

[dependencies]
core-p2p = { path = "../p2p", features = ["prost-message"] }
core-types = { path = "../types" }
core-serialization = { path = "../serialization" }

config-parser = { path = "../../common/config-parser" }

tentacle = "0.2.0-alpha.1"
log = "0.4"
futures = "0.1"
prost = "0.5"
bytes = "0.4"
tokio = "0.1"
serde_derive = "1.0"
serde = "1.0"

[dev-dependencies]
env_logger = "0.6"
