[package]
name = "muta-proto"
version = "0.1.0"
authors = ["Cryptape Technologies <contact@cryptape.com>"]
edition = "2018"
license = "Apache-2.0"

[lib]
name = "muta_proto"

[dependencies]
bytes = "0.4.11"
prost = "0.4.0"
prost-derive = "0.4.0"

[build-dependencies]
prost-build = "0.4.0"
