[package]
name = "core-p2p"
version = "0.1.0"
authors = ["Cryptape Technologies <contact@cryptape.com>"]
edition = "2018"

[dependencies]
tentacle = "0.2.0-alpha.5"
tentacle-discovery = "0.2.0"
tentacle-identify = "0.2.0"
tentacle-ping = "0.3.0"
generic-channel = { version = "0.2.0", features = [ "futures" ] }
env_logger = "0.6"
log = "0.4"
futures = "0.1"
parking_lot = "0.7"
bytes = "0.4"
prost = { version = "0.5", optional = true }
rand = "0.6"
# TODO: rename futures01 instead
futures03 = { package = "futures-preview", version = "=0.3.0-alpha.14", features = [ "compat" ] }


# Unfortunately, dev-dependencies cannot be optional.
[dev-dependencies]
prost-derive = "0.5"
tokio = "0.1"
runtime = "0.3.0-alpha.1"
runtime-raw = "0.3.0-alpha.1"
runtime-tokio = "0.3.0-alpha.2"

[features]
default = []
prost-message = ["prost"]

# [[example]]
# name = "transmission"
