[package]
name = "components-executor"
version = "0.1.0"
authors = ["Cryptape Technologies <contact@cryptape.com>"]
edition = "2018"

[dependencies]
core-runtime = { path = "../../core/runtime" }
core-storage = { path = "../../core/storage" }
core-types = { path = "../../core/types" }
core-context = { path = "../../core/context" }

cita-vm = "0.1"
log = "0.4"
futures = "0.1"
ethereum-types = "0.4"
hex = "0.3"
cita_trie = "0.3"

[dev-dependencies]
core-crypto = { path = "../../core/crypto" }
